-- AlterTable
ALTER TABLE "Appraisal" ADD COLUMN     "finalScore" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "grade" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "mdScore" INTEGER NOT NULL DEFAULT 0;
